### ISSUE TITLE
error,r version 3.3.1

### ISSUE THREAD

**Issue by gaodianzhuo** [WinVector/kcomp#1]
>results = find_clusters(data0)
> results
$nclusters
[1] 4

$pvals
[1] 0.00 0.00 0.00 0.39

$simplot
错误: 'as_tibble'不是'namespace:tibble'内的出口对象：

**Comment by JohnMount** [comment]
Sorry you are having trouble.  Please understand that this project is a worked example- not a fully re-usable library.

We've re-confirmed the included ".Rmd" file work under R 3.3.2.  I know it is unsatisfying, but I suggest re-installing R and the packages involved.  The p-values being zero merely means there is some evidence those components are not noise.  The simplot should not be a tible, but a ggplot2 plotting structure (which is for our examples).  The error message "Error: 'as_tibble' is not an export object within 'namespace: tibble':" suggests something is trying to convert the plot to a tbl.  

I would suggest only running the example code on actual data.frames, not tbls.
